apiVersion: apps/v1
kind: Deployment
metadata:
  name: serving-grpc
  labels:
    app: serving-grpc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: serving-grpc
  template:
    metadata:
      labels:
        app: serving-grpc
    spec:
      containers:
      - name: serving-grpc
        image: serving-grpc:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
