apiVersion: apps/v1
kind: Deployment
metadata:
  name: serving-grpc
  labels:
    app: serving-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serving-grpc
  template:
    metadata:
      labels:
        app: serving-grpc
    spec:
      containers:
      - name: serving-grpc
        image: asia-northeast1-docker.pkg.dev/sduality-analysis/prediction/serving-grpc:0.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SYSTEM_ENV
          value: "dev"
        resources:
          requests:
            cpu: 4000m
            memory: 500Mi
