apiVersion: v1
kind: Service
metadata:
  name: serving-grpc
spec:
  type: ClusterIP
  ports:
  - name: "grpc-port"
    protocol: "TCP"
    port: 8080
    targetPort: 8080
  selector:
    app: serving-grpc
